# Generated by Django 3.1.4 on 2020-12-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Titel dieser Iteration', max_length=100, verbose_name='Name')),
                ('moodle_course_id', models.PositiveSmallIntegerField(help_text='ID des zugehörigen Moodlekurses', verbose_name='Moodlekurs-ID')),
                ('active', models.BooleanField(blank=True, help_text='Ist diese Iteration aktuell atkiv?', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'BP',
                'verbose_name_plural': 'BPs',
                'ordering': ['-active'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField(verbose_name='Projekt-/Gruppennummer')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('ag', models.CharField(max_length=100, verbose_name='AG')),
                ('ag_mail', models.EmailField(max_length=254, verbose_name='AG E-Mail')),
                ('order_id', models.CharField(max_length=5, verbose_name='Pretix Order ID')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp', verbose_name='Zugehöriges BP')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['bp', 'nr'],
            },
        ),
        migrations.CreateModel(
            name='TL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp', verbose_name='Zugehöriges BP')),
            ],
            options={
                'verbose_name': 'Teamleitung',
                'verbose_name_plural': 'Teamleitungen',
                'ordering': ['bp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp', verbose_name='Zugehöriges BP')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bp.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Teilnehmende*r',
                'verbose_name_plural': 'Teilnehmende',
                'ordering': ['bp', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bp.tl', verbose_name='Zugehörige TL'),
        ),
    ]
