# Generated by Django 3.1.4 on 2020-12-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('requires_attention', models.BooleanField(blank=True, default=False, help_text='Benötigt diese Gruppe aktuell besondere Aufmerksamkeit durch das Organisationsteam?', verbose_name='Besondere Aufmerksamkeit')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.tl')),
            ],
            options={
                'verbose_name': 'TL Log',
                'verbose_name_plural': 'TL Logs',
            },
        ),
    ]
