# Generated by Django 3.1.5 on 2021-01-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0002_tllog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tllog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'TL Log', 'verbose_name_plural': 'TL Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('bp', 'nr'), ('bp', 'order_id')},
        ),
    ]
