# Generated by Django 3.1.5 on 2021-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0003_project_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ag_points',
            field=models.SmallIntegerField(default=-1, help_text='0-100', verbose_name='Punkte für den Implementierungsteil'),
        ),
        migrations.AddField(
            model_name='project',
            name='ag_points_justification',
            field=models.TextField(blank=True, verbose_name='Begründung'),
        ),
    ]
