# Generated by Django 3.1.5 on 2021-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0005_bp_pretix_event_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='student',
            name='moodle_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Moodle ID'),
        ),
    ]
