# Generated by Django 3.2.8 on 2021-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0008_tllog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tl',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Bestätigt'),
        ),
    ]
