# Generated by Django 3.2.8 on 2021-11-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0009_tl_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tllog',
            name='comment',
            field=models.TextField(blank=True, help_text='Interner Kommentar des Orga-Teams zu diesem Eintrag', verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='tllog',
            name='handled',
            field=models.BooleanField(blank=True, default=False, help_text='Das Log forderte eine Reaktion des Orga-Teams, die bereits durchgeführt wurde.', verbose_name='Erledigt'),
        ),
    ]
