# Generated by Django 3.2.8 on 2021-11-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0010_log_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLLogProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='tllog',
            name='status',
            field=models.SmallIntegerField(choices=[(-2, 'Schlecht'), (-1, 'Eher schlecht'), (0, 'Neutral'), (1, 'Eher gut'), (2, 'Gut')], default=0, help_text='Wie läuft es bei der Gruppe insgesamt aktuell?'),
        ),
        migrations.AlterField(
            model_name='tllog',
            name='text',
            field=models.TextField(help_text='Berichte kurz: Was war die Aktivität vergangene Woche? Hast du dich mit der Gruppe getroffen? Hattet ihr anderweitig Kontakt? Gab es ein AG Treffen? Gibt es Probleme?'),
        ),
        migrations.AddField(
            model_name='tllog',
            name='current_problems',
            field=models.ManyToManyField(blank=True, help_text='Trifft davon etwas bei der Gruppe zu?', to='bp.TLLogProblem'),
        ),
    ]
