# Generated by Django 3.2.8 on 2021-11-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0011_tllog_rich_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tllog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'TL-Log', 'verbose_name_plural': 'TL-Logs'},
        ),
        migrations.AlterModelOptions(
            name='tllogproblem',
            options={'verbose_name': 'TL-Log-Problem', 'verbose_name_plural': 'TL-Log-Probleme'},
        ),
        migrations.AlterField(
            model_name='tllog',
            name='current_problems',
            field=models.ManyToManyField(blank=True, help_text='Trifft davon etwas bei der Gruppe zu?', to='bp.TLLogProblem', verbose_name='Aktuelle Probleme'),
        ),
        migrations.AlterField(
            model_name='tllog',
            name='requires_attention',
            field=models.BooleanField(blank=True, default=False, help_text='Benötigt diese Gruppe aktuell besondere Aufmerksamkeit durch das Organisationsteam/sollten wir das Log besonders dringend lesen?', verbose_name='Besondere Aufmerksamkeit'),
        ),
    ]
