# Generated by Django 3.2.8 on 2021-12-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0013_tllog_meta_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLLogReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.tl')),
            ],
            options={
                'verbose_name': 'TL-Log-Erinnerung',
                'verbose_name_plural': 'TL-Log-Erinnerungen'
            },
        ),
    ]
