# Generated by Django 3.2.13 on 2022-07-21 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bp', '0015_auto_20220714_1435'), ('bp', '0016_auto_20220714_1621'), ('bp', '0017_project_ag_grade'), ('bp', '0018_auto_20220715_1515'), ('bp', '0019_auto_20220715_1542')]

    dependencies = [
        ('bp', '0014_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bp',
            name='ag_grading_end',
            field=models.DateField(default=datetime.date(2022, 7, 14), verbose_name='Ende der Notenabgabe durch die AGs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bp',
            name='ag_grading_start',
            field=models.DateField(default=datetime.date(2022, 7, 14), verbose_name='Beginn der Notenabgabe durch die AGs'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='ag_points',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ag_points_justification',
        ),
        migrations.CreateModel(
            name='AGGradeBeforeDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_points', models.SmallIntegerField(help_text='0-100', verbose_name='Punkte für den Implementierungsteil')),
                ('ag_points_justification', models.TextField(verbose_name='Begründung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
                'ordering': ['project', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AGGradeAfterDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_points', models.SmallIntegerField(help_text='0-100', verbose_name='Punkte für den Implementierungsteil')),
                ('ag_points_justification', models.TextField(verbose_name='Begründung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Bewertung (verspätet)',
                'verbose_name_plural': 'Bewertungen (verspätet)',
                'ordering': ['project', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='ag_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valid_grade', to='bp.aggradeafterdeadline', verbose_name='Derzeit gültige Bewertung'),
        ),
    ]
