# Generated by Django 3.2.13 on 2022-07-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0014_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tllogreminder',
            options={'verbose_name': 'TL-Log-Erinnerung', 'verbose_name_plural': 'TL-Log-Erinnerungen'},
        ),
        migrations.CreateModel(
            name='OrgaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(-2, 'Schlecht'), (-1, 'Eher schlecht'), (0, 'Neutral'), (1, 'Eher gut'), (2, 'Gut')], default=0, help_text='Wie läuft es bei der Gruppe insgesamt aktuell?')),
                ('text', models.TextField(help_text='Notizen zur Gruppe')),
                ('requires_attention', models.BooleanField(blank=True, default=False, help_text='Benötigt diese Gruppe aktuell besondere Aufmerksamkeit durch das Organisationsteam/sollten wir das Log besonders dringend lesen?', verbose_name='Besondere Aufmerksamkeit')),
                ('comment', models.TextField(blank=True, help_text='Interner Kommentar des Orga-Teams zu diesem Eintrag', verbose_name='Kommentar')),
                ('read', models.BooleanField(blank=True, default=False, verbose_name='Gelesen')),
                ('handled', models.BooleanField(blank=True, default=False, help_text='Das Log forderte eine Reaktion des Orga-Teams, die bereits durchgeführt wurde.', verbose_name='Erledigt')),
                ('good_log', models.NullBooleanField(default=None, verbose_name='Gutes Log?')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp')),
                ('current_problems', models.ManyToManyField(blank=True, help_text='Trifft davon etwas bei der Gruppe zu?', to='bp.TLLogProblem', verbose_name='Aktuelle Probleme')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.tl')),
            ],
            options={
                'verbose_name': 'Orga-Log',
                'verbose_name_plural': 'Orga-Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
