# Generated by Django 3.2.13 on 2022-07-14 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0014_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tllogreminder',
            options={'verbose_name': 'TL-Log-Erinnerung', 'verbose_name_plural': 'TL-Log-Erinnerungen'},
        ),
        migrations.AddField(
            model_name='bp',
            name='ag_grading_end',
            field=models.DateField(default=datetime.date(2022, 7, 14), verbose_name='Ende der Notenabgabe durch die AGs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bp',
            name='ag_grading_start',
            field=models.DateField(default=datetime.date(2022, 7, 14), verbose_name='Beginn der Notenabgabe durch die AGs'),
            preserve_default=False,
        ),
    ]
