# Generated by Django 3.2.13 on 2022-07-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0015_aggrades_restructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(-2, 'Schlecht'), (-1, 'Eher schlecht'), (0, 'Neutral'), (1, 'Eher gut'), (2, 'Gut')], default=0, help_text='Wie läuft es bei der Gruppe insgesamt aktuell?')),
                ('text', models.TextField(help_text='Notizen zur Gruppe')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.bp')),
                ('current_problems', models.ManyToManyField(blank=True, help_text='Trifft davon etwas bei der Gruppe zu?', to='bp.TLLogProblem', verbose_name='Aktuelle Probleme')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Orga-Log',
                'verbose_name_plural': 'Orga-Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
