# Generated by Django 3.2.13 on 2022-07-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0015_auto_20220706_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgalog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='orgalog',
            name='good_log',
        ),
        migrations.RemoveField(
            model_name='orgalog',
            name='read',
        ),
        migrations.RemoveField(
            model_name='orgalog',
            name='tl',
        ),
    ]
