# Generated by Django 3.2.13 on 2022-07-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0015_orgalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tllogreminder',
            options={'verbose_name': 'TL-Log-Erinnerung', 'verbose_name_plural': 'TL-Log-Erinnerungen'},
        ),
    ]
