# Generated by Django 3.2.13 on 2022-07-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0015_auto_20220714_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ag_points',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ag_points_justification',
        ),
        migrations.CreateModel(
            name='AGGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_points', models.SmallIntegerField(help_text='0-100', verbose_name='Punkte für den Implementierungsteil')),
                ('ag_points_justification', models.TextField(verbose_name='Begründung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
                'ordering': ['project', 'timestamp'],
            },
        ),
    ]
