# Generated by Django 3.2.13 on 2022-08-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0016_add_user_to_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Intervallname')),
                ('start', models.DateField(verbose_name='Beginn des Intervalls')),
                ('end', models.DateField(verbose_name='Ende des Intervalls')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bp.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Intervall für Zeiterfassung',
                'verbose_name_plural': 'Intervalle für Zeiterfassung',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSpentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Kategorie für Zeiterfassung',
                'verbose_name_plural': 'Kategorien für Zeiterfassung',
            },
        ),
        migrations.CreateModel(
            name='TimeTrackingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Stunden (h)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bp.timespentcategory', verbose_name='Kategorie')),
                ('interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bp.timeinterval', verbose_name='Zeitintervall')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bp.student', verbose_name='Teammitglied')),
            ],
            options={
                'verbose_name': 'Eintrag für Zeiterfassung',
                'verbose_name_plural': 'Einträge für Zeiterfassung',
            },
        ),
    ]
