# Generated by Django 3.2.13 on 2022-07-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0017_project_ag_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGGradeAfterDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_points', models.SmallIntegerField(help_text='0-100', verbose_name='Punkte für den Implementierungsteil')),
                ('ag_points_justification', models.TextField(verbose_name='Begründung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Bewertung (verspätet)',
                'verbose_name_plural': 'Bewertungen (verspätet)',
                'ordering': ['project', 'timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='ag_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valid_grade', to='bp.aggradeafterdeadline', verbose_name='Derzeit gültige Bewertung'),
        ),
    ]
