# Generated by Django 3.2.13 on 2022-07-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0018_auto_20220715_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AGGrade',
            new_name='AGGradeBeforeDeadline',
        ),
        migrations.CreateModel(
            name='AGGradeDeadlineForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_points', models.SmallIntegerField(help_text='0-100', verbose_name='Punkte für den Implementierungsteil')),
                ('ag_points_justification', models.TextField(verbose_name='Begründung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
