# Generated by Django 3.2.15 on 2022-10-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0018_tllog_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLLogTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Text, der den TLs als Vorlage angezeigt wird', verbose_name='Vorlagentext')),
                ('bp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bp.bp')),
            ],
            options={
                'verbose_name': 'TL-Log Vorlage',
                'verbose_name_plural': 'TL-Log Vorlagen',
            },
        ),
    ]
