# Generated by Django 3.2.15 on 2022-10-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0019_tllogtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Punkte für die Vorträge')),
                ('grade_notes', models.TextField(verbose_name='Notiz')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Bewertung der Vorträge',
                'verbose_name_plural': 'Bewertungen der Vorträge',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='DocsGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Punkte für die Dokumentation')),
                ('grade_notes', models.TextField(verbose_name='Notiz')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bp.project')),
            ],
            options={
                'verbose_name': 'Bewertung der Dokumentation',
                'verbose_name_plural': 'Bewertungen der Dokumentationen',
                'ordering': ['project'],
            },
        ),
    ]
