# Generated by Django 3.2.18 on 2023-08-16 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0022_auto_20230724_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchgrade',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)], verbose_name='Punkte für die Vorträge'),
        ),
    ]
