# Generated by Django 3.2.18 on 2023-08-16 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0023_alter_pitchgrade_grade_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsgrade',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(0)], verbose_name='Punkte für die Dokumentation'),
        ),
    ]
