# Generated by Django 3.2.20 on 2023-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0024_alter_docsgrade_grade_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Kurzer Titel'),
        ),
    ]
