# Generated by Django 3.2.20 on 2023-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0026_auto_20230914_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgalog',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
