# Generated by Django 3.2.20 on 2023-10-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0028_auto_20230920_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='bp',
            name='last_reminded',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der letzten Erinnerung, einen Log zu senden'),
        ),
    ]
