# Generated by Django 3.2.20 on 2023-10-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0031_tl_log_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TLLogReminder',
        ),
    ]
